apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset
  labels:
    tier: frontend
    app: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-label
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-label
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
