apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: rs-myapp
spec:
    selector:
      matchLabels:
        app: nginx-label
    replicas: 3
    template:
      metadata:
        name: nginx
        labels:
          app: nginx-label
          tier: frontend
      spec:
        containers:
          - name: nginx
            image: nginx
